#ifndef _INCLUDE_KJU_H
#define _INCLUDE_KJU_H

/*
 * File generated by StormLink from kju.fd
 * DO NOT EDIT
 * $VER: kju.library 1.0 (12-Apr-23)
 */
#ifdef __cplusplus
extern "C" {
#endif
#pragma amicall(KjuBase, 0x1e, KJU_AND(d0, d1))
#pragma amicall(KjuBase, 0x24, KJU_OR(d0, d1))
#pragma amicall(KjuBase, 0x2a, KJU_NOT(d0))
#pragma amicall(KjuBase, 0x30, KJU_NAND(d0, d1))
#pragma amicall(KjuBase, 0x36, KJU_NOR(d0, d1))
#pragma amicall(KjuBase, 0x3c, KJU_XOR(d0, d1))
#pragma amicall(KjuBase, 0x42, KJU_XNOR(d0, d1))
#pragma amicall(KjuBase, 0x48, KJU_IMP(d0, d1))
#pragma amicall(KjuBase, 0x4e, KJU_ABS(d0))
#pragma amicall(KjuBase, 0x54, KJU_MAX(d0, d1))
#pragma amicall(KjuBase, 0x5a, KJU_MIN(d0, d1))
#pragma amicall(KjuBase, 0x60, KJU_SWAP(d0, d1))
#pragma amicall(KjuBase, 0x66, KJU_REQUEST(d1, d2, d3))
#pragma amicall(KjuBase, 0x6c, KJU_REBOOT())
#ifdef __cplusplus
};
#endif
#endif
